'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

export type Locale =
  | 'fr'
  | 'en'
  | 'es'
  | 'pt'
  | 'de'
  | 'it'
  | 'ar'
  | 'bci'
  | 'dyu'
  | 'sw'
  | 'yo'
  | 'ha'
  | 'zh'
  | 'ja'
  | 'ru'
  | 'hi';

export interface LanguageInfo {
  code: Locale;
  name: string;
  nativeName: string;
  flag: string;
  region?: string;
}

export const AVAILABLE_LANGUAGES: LanguageInfo[] = [
  { code: 'fr', name: 'Français', nativeName: 'Français', flag: '🇫🇷', region: 'International / Côte d’Ivoire' },
  { code: 'en', name: 'Anglais', nativeName: 'English', flag: '🇬🇧', region: 'International' },
  { code: 'es', name: 'Espagnol', nativeName: 'Español', flag: '🇪🇸', region: 'Europe / Amérique Latine' },
  { code: 'pt', name: 'Portugais', nativeName: 'Português', flag: '🇵🇹', region: 'Europe / Brésil / Angola' },
  { code: 'de', name: 'Allemand', nativeName: 'Deutsch', flag: '🇩🇪', region: 'Europe' },
  { code: 'it', name: 'Italien', nativeName: 'Italiano', flag: '🇮🇹', region: 'Europe' },
  { code: 'ar', name: 'Arabe', nativeName: 'العربية', flag: '🇸🇦', region: 'Moyen-Orient / Afrique du Nord' },
  { code: 'bci', name: 'Baoulé', nativeName: 'Bawle', flag: '🇨🇮', region: 'Côte d’Ivoire' },
  { code: 'dyu', name: 'Dioula', nativeName: 'Julakan', flag: '🇨🇮', region: 'Côte d’Ivoire / Afrique de l’Ouest' },
  { code: 'sw', name: 'Swahili', nativeName: 'Kiswahili', flag: '🇰🇪', region: 'Afrique de l’Est' },
  { code: 'yo', name: 'Yoruba', nativeName: 'Èdè Yorùbá', flag: '🇳🇬', region: 'Afrique de l’Ouest' },
  { code: 'ha', name: 'Haoussa', nativeName: 'Harshen Hausa', flag: '🇳🇬', region: 'Afrique de l’Ouest' },
  { code: 'zh', name: 'Chinois', nativeName: '中文 (简体)', flag: '🇨🇳', region: 'Asie' },
  { code: 'ja', name: 'Japonais', nativeName: '日本語', flag: '🇯🇵', region: 'Asie' },
  { code: 'ru', name: 'Russe', nativeName: 'Русский', flag: '🇷🇺', region: 'Europe de l’Est' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', flag: '🇮🇳', region: 'Asie du Sud' },
];

export const translations: Record<Locale, Record<string, string>> = {
  fr: {
    music: "Musique",
    videos: "Vidéos",
    home: "Accueil",
    playlists: "Playlists",
    favorites: "Favoris",
    history: "Historique",
    settings: "Réglages",
    searchPlaceholder: "Rechercher morceaux, vidéos, albums, artistes, playlists...",
    filterTracks: "Filtrer les morceaux...",
    title: "Titre",
    artist: "Artiste",
    album: "Album",
    duration: "Durée",
    size: "Taille",
    dateAdded: "Date d'ajout",
    importFiles: "Fichiers",
    importFolder: "Dossier",
    demos: "Démos",
    localStats: "Statistiques locales",
    lyrics: "Paroles",
    transcribe: "Transcrire avec Gemini IA",
    editMetadata: "Modifier les métadonnées",
    removeFromLib: "Retirer de la bibliothèque",
    search: "Rechercher",
    tracksCount: "piste(s) audio indexée(s)",
    noTracks: "Aucun titre correspondant trouvé",
    albums: "Albums",
    artists: "Artistes",
    genres: "Genres",
    folders: "Dossiers",
    tracksTab: "Titres",
    playNow: "Lire maintenant",
    playNext: "Lire juste après",
    addToQueue: "Ajouter à la file",
    addToPlaylist: "Ajouter à une playlist",
    fileInfo: "Informations du fichier",
    deleteLyrics: "Supprimer les paroles",
    language: "Langue",
    theme: "Thème",
    nowPlaying: "En cours de lecture",
    volume: "Volume",
    sleepTimer: "Minuteur de sommeil",
    crossfade: "Fondu enchaîné",
    visualizer: "Visualiseur",
    vinyl: "Disque Vinyle",
    visualizerBars: "Barres de Fréquence",
    customBg: "Arrière-plan personnalisé",
    normalizer: "Normalisation du Volume",
    autoPlaylists: "Générer automatiquement des playlists",
  },
  en: {
    music: "Music",
    videos: "Videos",
    home: "Home",
    playlists: "Playlists",
    favorites: "Favorites",
    history: "History",
    settings: "Settings",
    searchPlaceholder: "Search tracks, videos, albums, artists, playlists...",
    filterTracks: "Filter tracks...",
    title: "Title",
    artist: "Artist",
    album: "Album",
    duration: "Duration",
    size: "Size",
    dateAdded: "Date added",
    importFiles: "Files",
    importFolder: "Folder",
    demos: "Demos",
    localStats: "Local statistics",
    lyrics: "Lyrics",
    transcribe: "Transcribe with Gemini AI",
    editMetadata: "Edit metadata",
    removeFromLib: "Remove from library",
    search: "Search",
    tracksCount: "indexed audio track(s)",
    noTracks: "No matching tracks found",
    albums: "Albums",
    artists: "Artists",
    genres: "Genres",
    folders: "Folders",
    tracksTab: "Tracks",
    playNow: "Play now",
    playNext: "Play next",
    addToQueue: "Add to queue",
    addToPlaylist: "Add to playlist",
    fileInfo: "File information",
    deleteLyrics: "Delete lyrics",
    language: "Language",
    theme: "Theme",
    nowPlaying: "Now Playing",
    volume: "Volume",
    sleepTimer: "Sleep Timer",
    crossfade: "Crossfade",
    visualizer: "Visualizer",
    vinyl: "Vinyl Record",
    visualizerBars: "Frequency Bars",
    customBg: "Custom Background",
    normalizer: "Volume Normalization",
    autoPlaylists: "Auto-Generate Playlists",
  },
  es: {
    music: "Música",
    videos: "Vídeos",
    home: "Inicio",
    playlists: "Listas de reproducción",
    favorites: "Favoritos",
    history: "Historial",
    settings: "Ajustes",
    searchPlaceholder: "Buscar pistas, vídeos, álbumes...",
    filterTracks: "Filtrar pistas...",
    title: "Título",
    artist: "Artista",
    album: "Álbum",
    duration: "Duración",
    size: "Tamaño",
    dateAdded: "Fecha añadida",
    importFiles: "Archivos",
    importFolder: "Carpeta",
    demos: "Demos",
    localStats: "Estadísticas locales",
    lyrics: "Letras",
    transcribe: "Transcribir con IA",
    editMetadata: "Editar metadatos",
    removeFromLib: "Eliminar de la biblioteca",
    search: "Buscar",
    tracksCount: "pistas indexadas",
    noTracks: "No se encontraron pistas",
    albums: "Álbumes",
    artists: "Artistas",
    genres: "Géneros",
    folders: "Carpetas",
    tracksTab: "Pistas",
    playNow: "Reproducir ahora",
    playNext: "Reproducir siguiente",
    addToQueue: "Añadir a la cola",
    addToPlaylist: "Añadir a lista",
    fileInfo: "Información del archivo",
    deleteLyrics: "Eliminar letra",
    language: "Idioma",
    theme: "Tema",
    nowPlaying: "En reproducción",
    volume: "Volumen",
    sleepTimer: "Temporizador de apagado",
    crossfade: "Fundido cruzado",
    visualizer: "Visualizador",
    vinyl: "Disco de vinilo",
    visualizerBars: "Barras de frecuencia",
    customBg: "Fondo personalizado",
    normalizer: "Normalización de volumen",
    autoPlaylists: "Generar listas automáticas",
  },
  pt: {
    music: "Música",
    videos: "Vídeos",
    home: "Início",
    playlists: "Playlists",
    favorites: "Favoritos",
    history: "Histórico",
    settings: "Definições",
    searchPlaceholder: "Pesquisar faixas, vídeos, álbuns...",
    filterTracks: "Filtrar faixas...",
    title: "Título",
    artist: "Artista",
    album: "Álbum",
    duration: "Duração",
    size: "Tamanho",
    dateAdded: "Adicionado em",
    importFiles: "Ficheiros",
    importFolder: "Pasta",
    demos: "Demos",
    localStats: "Estatísticas locais",
    lyrics: "Letras",
    transcribe: "Transcrever com IA",
    editMetadata: "Editar metadados",
    removeFromLib: "Remover da biblioteca",
    search: "Pesquisar",
    tracksCount: "faixas indexadas",
    noTracks: "Nenhuma faixa encontrada",
    albums: "Álbuns",
    artists: "Artistas",
    genres: "Géneros",
    folders: "Pastas",
    tracksTab: "Faixas",
    playNow: "Tocar agora",
    playNext: "Tocar a seguir",
    addToQueue: "Adicionar à fila",
    addToPlaylist: "Adicionar à playlist",
    fileInfo: "Informações do ficheiro",
    deleteLyrics: "Eliminar letras",
    language: "Idioma",
    theme: "Tema",
    nowPlaying: "A reproduzir",
    volume: "Volume",
    sleepTimer: "Temporizador",
    crossfade: "Crossfade",
    visualizer: "Visualizador",
    vinyl: "Disco de Vinil",
    visualizerBars: "Barras de Frequência",
    customBg: "Fundo Personalizado",
    normalizer: "Normalização de Volume",
    autoPlaylists: "Gerar playlists automáticas",
  },
  de: {
    music: "Musik",
    videos: "Videos",
    home: "Startseite",
    playlists: "Wiedergabelisten",
    favorites: "Favoriten",
    history: "Verlauf",
    settings: "Einstellungen",
    searchPlaceholder: "Titel, Videos, Alben suchen...",
    filterTracks: "Titel filtern...",
    title: "Titel",
    artist: "Künstler",
    album: "Album",
    duration: "Dauer",
    size: "Größe",
    dateAdded: "Hinzugefügt am",
    importFiles: "Dateien",
    importFolder: "Ordner",
    demos: "Demos",
    localStats: "Lokale Statistiken",
    lyrics: "Songtext",
    transcribe: "Mit KI transkribieren",
    editMetadata: "Metadaten bearbeiten",
    removeFromLib: "Aus Mediathek entfernen",
    search: "Suchen",
    tracksCount: "Titel indexiert",
    noTracks: "Keine passenden Titel gefunden",
    albums: "Alben",
    artists: "Künstler",
    genres: "Genres",
    folders: "Ordner",
    tracksTab: "Titel",
    playNow: "Jetzt abspielen",
    playNext: "Als Nächstes spielen",
    addToQueue: "Zur Warteschlange hinzufügen",
    addToPlaylist: "Zur Playlist hinzufügen",
    fileInfo: "Dateiinformationen",
    deleteLyrics: "Songtext löschen",
    language: "Sprache",
    theme: "Design",
    nowPlaying: "Aktueller Titel",
    volume: "Lautstärke",
    sleepTimer: "Schlaf-Timer",
    crossfade: "Überblendung",
    visualizer: "Visualizer",
    vinyl: "Schallplatte",
    visualizerBars: "Frequenzbalken",
    customBg: "Eigener Hintergrund",
    normalizer: "Lautstärke-Normalisierung",
    autoPlaylists: "Automatische Playlists erstellen",
  },
  it: {
    music: "Musica",
    videos: "Video",
    home: "Home",
    playlists: "Playlist",
    favorites: "Preferiti",
    history: "Cronologia",
    settings: "Impostazioni",
    searchPlaceholder: "Cerca brani, video, album...",
    filterTracks: "Filtra brani...",
    title: "Titolo",
    artist: "Artista",
    album: "Album",
    duration: "Durata",
    size: "Dimensione",
    dateAdded: "Aggiunto il",
    importFiles: "File",
    importFolder: "Cartella",
    demos: "Demo",
    localStats: "Statistiche locali",
    lyrics: "Testi",
    transcribe: "Trascrivi con IA",
    editMetadata: "Modifica metadati",
    removeFromLib: "Rimuovi dalla libreria",
    search: "Cerca",
    tracksCount: "brani indicizzati",
    noTracks: "Nessun brano trovato",
    albums: "Album",
    artists: "Artisti",
    genres: "Generi",
    folders: "Cartelle",
    tracksTab: "Brani",
    playNow: "Riproduci ora",
    playNext: "Riproduci dopo",
    addToQueue: "Aggiungi alla coda",
    addToPlaylist: "Aggiungi alla playlist",
    fileInfo: "Info file",
    deleteLyrics: "Elimina testi",
    language: "Lingua",
    theme: "Tema",
    nowPlaying: "In riproduzione",
    volume: "Volume",
    sleepTimer: "Timer spegnimento",
    crossfade: "Dissolvenza incrociata",
    visualizer: "Visualizzatore",
    vinyl: "Disco in vinile",
    visualizerBars: "Barre di frequenza",
    customBg: "Sfondo personalizzato",
    normalizer: "Normalizzazione volume",
    autoPlaylists: "Genera playlist automatiche",
  },
  ar: {
    music: "الموسيقى",
    videos: "الفيديوهات",
    home: "الرئيسية",
    playlists: "قوائم التشغيل",
    favorites: "المفضلة",
    history: "السجل",
    settings: "الإعدادات",
    searchPlaceholder: "البحث عن المقاطع، الفيديوهات...",
    filterTracks: "تصفية المقاطع...",
    title: "العنوان",
    artist: "الفنان",
    album: "الألبوم",
    duration: "المدة",
    size: "الحجم",
    dateAdded: "تاريخ الإضافة",
    importFiles: "ملفات",
    importFolder: "مجلد",
    demos: "عروض تجريبية",
    localStats: "إحصائيات محلية",
    lyrics: "الكلمات",
    transcribe: "نسخ بالذكاء الاصطناعي",
    editMetadata: "تعديل البيانات",
    removeFromLib: "إزالة من المكتبة",
    search: "بحث",
    tracksCount: "مسار صوتي",
    noTracks: "لم يتم العثور على نتائج",
    albums: "الألبومات",
    artists: "الفنانون",
    genres: "الأنواع",
    folders: "المجلدات",
    tracksTab: "المقاطع",
    playNow: "تشغيل الآن",
    playNext: "تشغيل التالي",
    addToQueue: "إضافة للانتظار",
    addToPlaylist: "إضافة لقائمة",
    fileInfo: "معلومات الملف",
    deleteLyrics: "حذف الكلمات",
    language: "اللغة",
    theme: "المظهر",
    nowPlaying: "قيد التشغيل",
    volume: "مستوى الصوت",
    sleepTimer: "مؤقت النوم",
    crossfade: "التلاشي المتقاطع",
    visualizer: "المؤثرات البصرية",
    vinyl: "أسطوانة فينيل",
    visualizerBars: "أشرطة التردد",
    customBg: "خلفية مخصصة",
    normalizer: "موازنة الصوت",
    autoPlaylists: "إنشاء قوائم تلقائية",
  },
  bci: {
    music: "Ngua",
    videos: "Videow",
    home: "Aulo",
    playlists: "Ngua Kpɛlɛ",
    favorites: "Ngua Kpa",
    history: "Ngua Mɛn Titin",
    settings: "Kplan",
    searchPlaceholder: "Kpinngbi ngua, videow, albom...",
    filterTracks: "Fa ngua nian...",
    title: "Dunman",
    artist: "Nguatofue",
    album: "Albom",
    duration: "Blɛ",
    size: "Danlɛ",
    dateAdded: "Cen nga fa wlɛli nun",
    importFiles: "Fisie mun",
    importFolder: "Dosie",
    demos: "Sanzan",
    localStats: "Sran nuan kalɛ",
    lyrics: "Nde nuan",
    transcribe: "Kɛlɛ nde nuan nin IA",
    editMetadata: "Kaci dunman nin nuan",
    removeFromLib: "Tu i nun",
    search: "Kunndɛ",
    tracksCount: "ngua ngba",
    noTracks: "Wunman ngua fi",
    albums: "Albom mun",
    artists: "Nguatofue mun",
    genres: "Ngua wafa wafa",
    folders: "Dosie mun",
    tracksTab: "Ngua mun",
    playNow: "Bɔ i siɛn su",
    playNext: "Bɔ i sin",
    addToQueue: "Wlɛ i nun",
    addToPlaylist: "Kɛlɛ i kpɛlɛ nun",
    fileInfo: "Fisie nde",
    deleteLyrics: "Nunnun nde nuan",
    language: "Aniɛn",
    theme: "Nzuɛ",
    nowPlaying: "Ɔ su bo",
    volume: "Nuan tɛnngɛlɛ",
    sleepTimer: "Lafilɛ blɛ",
    crossfade: "Ngua koto nuan",
    visualizer: "Nianlɛ",
    vinyl: "Diski Vinil",
    visualizerBars: "Bare mun",
    customBg: "Akunndan lufle",
    normalizer: "Nuan jinjilɛ",
    autoPlaylists: "Yaci plélisi kpa",
  },
  dyu: {
    music: "Fɔli",
    videos: "Videow",
    home: "So",
    playlists: "Fɔli Kafow",
    favorites: "Fɔli Diyalenw",
    history: "Fɔlen Kɔrɔw",
    settings: "Labɛnw",
    searchPlaceholder: "Fɔli, video, dɔnkili ɲini...",
    filterTracks: "Fɔliw tɛgɛ...",
    title: "Tɔgɔ",
    artist: "Dɔnkilidala",
    album: "Albom",
    duration: "Waati",
    size: "Hakɛ",
    dateAdded: "Don don",
    importFiles: "Fisiyew",
    importFolder: "Dosiyew",
    demos: "Nɛgɛkanw",
    localStats: "Jatebaw",
    lyrics: "Kuma nuan",
    transcribe: "Kuma sɛbɛn ni IA ye",
    editMetadata: "Tɔgɔ yɛlɛma",
    removeFromLib: "A bɔ a la",
    search: "Ɲini",
    tracksCount: "fɔli hakɛ",
    noTracks: "Foyi ma sɔrɔ",
    albums: "Albomw",
    artists: "Fɔlikɛlaw",
    genres: "Fɔli suguya",
    folders: "Dosiyew",
    tracksTab: "Fɔliw",
    playNow: "A fɔ sisan",
    playNext: "A fɔ a kɔfɛ",
    addToQueue: "A bila a kɔ",
    addToPlaylist: "A bila kafo kɔnɔ",
    fileInfo: "Kunnafoniw",
    deleteLyrics: "Kuma josi",
    language: "Kan",
    theme: "Ja",
    nowPlaying: "Bɛ fɔ kan",
    volume: "Kankan",
    sleepTimer: "Sunɔgɔ waati",
    crossfade: "Kɔnɔfɛ fɔli",
    visualizer: "Filɛlikɛlan",
    vinyl: "Vinili Disiki",
    visualizerBars: "Jafaranw",
    customBg: "Kɔfɛ ja",
    normalizer: "Kankan ladon",
    autoPlaylists: "Kafo dilan a yɛrɛ ma",
  },
  sw: {
    music: "Muziki",
    videos: "Video",
    home: "Nyumbani",
    playlists: "Orodha za Nyimbo",
    favorites: "Nyimbo Pendwa",
    history: "Historia",
    settings: "Mipangilio",
    searchPlaceholder: "Tafuta nyimbo, video, albamu...",
    filterTracks: "Chuja nyimbo...",
    title: "Jina",
    artist: "Msanii",
    album: "Albamu",
    duration: "Muda",
    size: "Ukubwa",
    dateAdded: "Tarehe ya kuongezwa",
    importFiles: "Faili",
    importFolder: "Folda",
    demos: "Sampuli",
    localStats: "Takwimu",
    lyrics: "Mashairi",
    transcribe: "Nakili kwa AI",
    editMetadata: "Hariri maelezo",
    removeFromLib: "Ondoa kwenye maktaba",
    search: "Tafuta",
    tracksCount: "nyimbo zilizopo",
    noTracks: "Hakuna wimbo uliopatikana",
    albums: "Albamu",
    artists: "Wasanii",
    genres: "Aina za Muziki",
    folders: "Folda",
    tracksTab: "Nyimbo",
    playNow: "Cheza sasa",
    playNext: "Cheza inayofuata",
    addToQueue: "Weka kwenye foleni",
    addToPlaylist: "Weka kwenye orodha",
    fileInfo: "Taarifa za faili",
    deleteLyrics: "Futa mashairi",
    language: "Lugha",
    theme: "Mandhari",
    nowPlaying: "Inacheza Sasa",
    volume: "Sauti",
    sleepTimer: "Kipima Muda cha Kulala",
    crossfade: "Mshikamano wa Sauti",
    visualizer: "Kionyeshi cha Sauti",
    vinyl: "Sahani ya Vinyl",
    visualizerBars: "Pau za Masafa",
    customBg: "Picha ya Mandhari",
    normalizer: "Usawazishaji wa Sauti",
    autoPlaylists: "Tengeneza Orodha Kiotomatiki",
  },
  yo: {
    music: "Orin",
    videos: "Fídíò",
    home: "Ilé",
    playlists: "Àkójọ Orin",
    favorites: "Àwọn Ayànfẹ́",
    history: "Ìtàn Orin",
    settings: "Ètò",
    searchPlaceholder: "Wá orin, fídíò, àwọn àwo...",
    filterTracks: "Ṣe àlẹmọ orin...",
    title: "Àkọlé",
    artist: "Olórin",
    album: "Àwo",
    duration: "Àkókò",
    size: "Ìwọ̀n",
    dateAdded: "Ọjọ́ tí a fi kún",
    importFiles: "Àwọn Fáìlì",
    importFolder: "Àpò Fáìlì",
    demos: "Àpẹẹrẹ",
    localStats: "Àwọn Ìṣirò",
    lyrics: "Ọ̀rọ̀ Orin",
    transcribe: "Kọ ọ̀rọ̀ orin pẹ̀lú AI",
    editMetadata: "Ṣatunṣe alaye",
    removeFromLib: "Yọ kuro ninu ile-ikawe",
    search: "Ṣe àwárí",
    tracksCount: "orin ti a kọ silẹ",
    noTracks: "Kò sí orin kankan",
    albums: "Àwọn Àwo",
    artists: "Àwọn Olórin",
    genres: "Ẹ̀yà Orin",
    folders: "Àwọn Àpò",
    tracksTab: "Àwọn Orin",
    playNow: "Gbó orin báyìí",
    playNext: "Gbó orin tí ó tẹ̀lé e",
    addToQueue: "Fi kún ìtòlẹ́sẹẹsẹ",
    addToPlaylist: "Fi kún àkójọ",
    fileInfo: "Àlàyé fáìlì",
    deleteLyrics: "Pa ọ̀rọ̀ orin rẹ́",
    language: "Èdè",
    theme: "Àwọ̀ Ìbòjú",
    nowPlaying: "Orin tó ń kọ",
    volume: "Ipele Ohùn",
    sleepTimer: "Aago oorun",
    crossfade: "Àkópọ̀ orin",
    visualizer: "Àfihàn Ìṣẹ́lẹ̀ Ohùn",
    vinyl: "Àwo Orin Fáínìlì",
    visualizerBars: "Ipele Ohùn",
    customBg: "Àwòrán Ẹ̀yìn",
    normalizer: "Ìṣètò Ipele Ohùn",
    autoPlaylists: "Ṣe Àkójọ Aifọwọyi",
  },
  ha: {
    music: "Waƙa",
    videos: "Bidiyoyi",
    home: "Gida",
    playlists: "Jerin Waƙoƙi",
    favorites: "Waɗanda aka fi so",
    history: "Tarihi",
    settings: "Saituna",
    searchPlaceholder: "Bincika waƙoƙi, bidiyo, kundi...",
    filterTracks: "Tace waƙoƙi...",
    title: "Take",
    artist: "Mawaƙi",
    album: "Kundi",
    duration: "Tsawon lokaci",
    size: "Girma",
    dateAdded: "Ranar ƙarawa",
    importFiles: "Fayiloli",
    importFolder: "Jaka",
    demos: "Misalai",
    localStats: "Kididdiga",
    lyrics: "Kalaman waƙa",
    transcribe: "Fassara da AI",
    editMetadata: "Gyara bayanai",
    removeFromLib: "Cire daga ɗakin karatu",
    search: "Bincika",
    tracksCount: "waƙoƙin da ke ciki",
    noTracks: "Ba a sami waƙa ba",
    albums: "Kundaye",
    artists: "Mawaƙa",
    genres: "Nau'in Waƙa",
    folders: "Jakunkuna",
    tracksTab: "Waƙoƙi",
    playNow: "Kunna yanzu",
    playNext: "Kunna na gaba",
    addToQueue: "Ƙara zuwa jeri",
    addToPlaylist: "Ƙara zuwa jerin waƙoƙi",
    fileInfo: "Bayanin fayil",
    deleteLyrics: "Goge kalaman waƙa",
    language: "Harshe",
    theme: "Salo",
    nowPlaying: "Ana Kunna Yanzu",
    volume: "Ƙarar Sauti",
    sleepTimer: "Ƙararrawar Barci",
    crossfade: "Haɗakar Sauti",
    visualizer: "Mai nuna sauti",
    vinyl: "Faifan Waƙa",
    visualizerBars: "Sandunan Sauti",
    customBg: "Bayan Fage",
    normalizer: "Daidaita Ƙarar Sauti",
    autoPlaylists: "Ƙirƙiri Jerin Waƙoƙi Masu Wayo",
  },
  zh: {
    music: "音乐",
    videos: "视频",
    home: "首页",
    playlists: "播放列表",
    favorites: "收藏夹",
    history: "播放历史",
    settings: "设置",
    searchPlaceholder: "搜索歌曲、视频、专辑、艺术家...",
    filterTracks: "筛选歌曲...",
    title: "标题",
    artist: "艺术家",
    album: "专辑",
    duration: "时长",
    size: "大小",
    dateAdded: "添加日期",
    importFiles: "导入文件",
    importFolder: "导入文件夹",
    demos: "演示音频",
    localStats: "本地统计",
    lyrics: "歌词",
    transcribe: "AI歌词转录",
    editMetadata: "编辑元数据",
    removeFromLib: "从媒体库移除",
    search: "搜索",
    tracksCount: "首已索引音频",
    noTracks: "未找到匹配曲目",
    albums: "专辑",
    artists: "艺术家",
    genres: "流派",
    folders: "文件夹",
    tracksTab: "曲目",
    playNow: "立即播放",
    playNext: "下一首播放",
    addToQueue: "添加到队列",
    addToPlaylist: "添加到歌单",
    fileInfo: "文件信息",
    deleteLyrics: "删除歌词",
    language: "语言",
    theme: "主题",
    nowPlaying: "正在播放",
    volume: "音量",
    sleepTimer: "睡眠定时器",
    crossfade: "淡入淡出",
    visualizer: "可视化效果",
    vinyl: "黑胶唱片",
    visualizerBars: "频谱条",
    customBg: "自定义壁纸",
    normalizer: "音量均衡",
    autoPlaylists: "自动生成歌单",
  },
  ja: {
    music: "音楽",
    videos: "動画",
    home: "ホーム",
    playlists: "プレイリスト",
    favorites: "お気に入り",
    history: "再生履歴",
    settings: "設定",
    searchPlaceholder: "曲、動画、アルバム、アーティストを検索...",
    filterTracks: "曲を絞り込み...",
    title: "タイトル",
    artist: "アーティスト",
    album: "アルバム",
    duration: "再生時間",
    size: "サイズ",
    dateAdded: "追加日時",
    importFiles: "ファイル追加",
    importFolder: "フォルダ追加",
    demos: "デモ曲",
    localStats: "ライブラリ統計",
    lyrics: "歌詞",
    transcribe: "AI歌詞自動書き起こし",
    editMetadata: "メタデータ編集",
    removeFromLib: "ライブラリから削除",
    search: "検索",
    tracksCount: "曲インデックス済み",
    noTracks: "一致する曲がありません",
    albums: "アルバム",
    artists: "アーティスト",
    genres: "ジャンル",
    folders: "フォルダ",
    tracksTab: "トラック",
    playNow: "今すぐ再生",
    playNext: "次に再生",
    addToQueue: "キューに追加",
    addToPlaylist: "プレイリストに追加",
    fileInfo: "ファイル詳細",
    deleteLyrics: "歌詞を削除",
    language: "言語",
    theme: "テーマ",
    nowPlaying: "再生中",
    volume: "音量",
    sleepTimer: "スリープタイマー",
    crossfade: "クロスフェード",
    visualizer: "ビジュアライザー",
    vinyl: "レコード盤",
    visualizerBars: "周波数バー",
    customBg: "カスタム背景",
    normalizer: "音量均一化",
    autoPlaylists: "プレイリスト自動作成",
  },
  ru: {
    music: "Музыка",
    videos: "Видео",
    home: "Главная",
    playlists: "Плейлисты",
    favorites: "Избранное",
    history: "История",
    settings: "Настройки",
    searchPlaceholder: "Поиск треков, видео, альбомов...",
    filterTracks: "Фильтр треков...",
    title: "Название",
    artist: "Исполнитель",
    album: "Альбом",
    duration: "Длительность",
    size: "Размер",
    dateAdded: "Дата добавления",
    importFiles: "Файлы",
    importFolder: "Папка",
    demos: "Демо",
    localStats: "Статистика",
    lyrics: "Текст песни",
    transcribe: "Транскрипция с AI",
    editMetadata: "Изменить метаданные",
    removeFromLib: "Удалить из медиатеки",
    search: "Поиск",
    tracksCount: "треков проиндексировано",
    noTracks: "Треки не найдены",
    albums: "Альбомы",
    artists: "Исполнители",
    genres: "Жанры",
    folders: "Папки",
    tracksTab: "Треки",
    playNow: "Играть сейчас",
    playNext: "Играть следующим",
    addToQueue: "В очередь",
    addToPlaylist: "В плейлист",
    fileInfo: "Информация о файле",
    deleteLyrics: "Удалить текст",
    language: "Язык",
    theme: "Тема",
    nowPlaying: "Сейчас играет",
    volume: "Громкость",
    sleepTimer: "Таймер сна",
    crossfade: "Кроссфейд",
    visualizer: "Визуализатор",
    vinyl: "Виниловая пластинка",
    visualizerBars: "Полосы частот",
    customBg: "Пользовательский фон",
    normalizer: "Нормализация звука",
    autoPlaylists: "Автоматические плейлисты",
  },
  hi: {
    music: "संगीत",
    videos: "वीडियो",
    home: "होम",
    playlists: "प्लेलिस्ट",
    favorites: "पसंदीदा",
    history: "इतिहास",
    settings: "सेटिंग्स",
    searchPlaceholder: "गाने, वीडियो, एल्बम, कलाकार खोजें...",
    filterTracks: "गाने फ़िल्टर करें...",
    title: "शीर्षक",
    artist: "कलाकार",
    album: "एल्बम",
    duration: "अवधि",
    size: "आकार",
    dateAdded: "जोड़े जाने की तारीख",
    importFiles: "फ़ाइलें जोड़ें",
    importFolder: "फ़ोल्डर जोड़ें",
    demos: "डेमो ट्रैक्स",
    localStats: "सांख्यिकी",
    lyrics: "गीत के बोल",
    transcribe: "AI द्वारा ट्रांसक्राइब",
    editMetadata: "मेटाडेटा संपादित करें",
    removeFromLib: "लाइब्रेरी से हटाएं",
    search: "खोजें",
    tracksCount: "गाने इंडेक्स किए गए",
    noTracks: "कोई गाना नहीं मिला",
    albums: "एल्बम",
    artists: "कलाकार",
    genres: "शैलियां",
    folders: "फ़ोल्डर्स",
    tracksTab: "गाने",
    playNow: "अभी चलाएं",
    playNext: "अगला चलाएं",
    addToQueue: "कतार में जोड़ें",
    addToPlaylist: "प्लेलिस्ट में जोड़ें",
    fileInfo: "फ़ाइल विवरण",
    deleteLyrics: "गीत के बोल हटाएं",
    language: "भाषा",
    theme: "थीम",
    nowPlaying: "अब बज रहा है",
    volume: "आवाज़ (वॉल्यूम)",
    sleepTimer: "स्लीप टाइमर",
    crossfade: "क्रॉसफ़ेड",
    visualizer: "विज़ुअलाइज़र",
    vinyl: "विनाइल रिकॉर्ड",
    visualizerBars: "फ़्रीक्वेंसी बार",
    customBg: "कस्टम वॉलपेपर",
    normalizer: "वॉल्यूम नॉर्मलाइज़ेशन",
    autoPlaylists: "ऑटो प्लेलिस्ट बनाएं",
  },
};

export type TranslationKey = keyof typeof translations.fr;

interface LanguageContextType {
  locale: Locale;
  availableLanguages: LanguageInfo[];
  t: (key: TranslationKey | string) => string;
  setLocale: (locale: Locale) => void;
  currentLanguage: LanguageInfo;
}

const LanguageContext = createContext<LanguageContextType | null>(null);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [locale, setLocaleState] = useState<Locale>('fr');

  useEffect(() => {
    const saved = localStorage.getItem('app_locale') as Locale;
    if (saved && AVAILABLE_LANGUAGES.some(l => l.code === saved)) {
      setLocaleState(saved);
    }
  }, []);

  const setLocale = (newLocale: Locale) => {
    setLocaleState(newLocale);
    localStorage.setItem('app_locale', newLocale);
    window.dispatchEvent(new Event('app-locale-changed'));
  };

  const t = (key: TranslationKey | string): string => {
    const currentDict = translations[locale] || translations['fr'];
    return currentDict[key] || translations['fr'][key] || translations['en'][key] || String(key);
  };

  const currentLanguage = AVAILABLE_LANGUAGES.find(l => l.code === locale) || AVAILABLE_LANGUAGES[0];

  return (
    <LanguageContext.Provider value={{ locale, availableLanguages: AVAILABLE_LANGUAGES, t, setLocale, currentLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
